# Generated by Django 3.0.6 on 2020-05-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_order_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_history',
        ),
    ]
