# Generated by Django 3.0.5 on 2020-05-15 17:23

import checkout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_num',
            field=models.CharField(max_length=255, validators=[checkout.models.card_num]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvc',
            field=models.CharField(max_length=3, validators=[checkout.models.cvc_num]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_year',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='zip',
            field=models.CharField(max_length=255, validators=[checkout.models.zip_info]),
        ),
    ]
