# Generated by Django 3.0.6 on 2020-05-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('computer_products', models.ManyToManyField(blank=True, null=True, to='computers.computers')),
                ('game_products', models.ManyToManyField(blank=True, null=True, to='games.games')),
            ],
        ),
    ]
