# Generated by Django 3.0.6 on 2020-05-06 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='game_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('onsale', models.BooleanField()),
                ('description', models.CharField(blank=True, max_length=999)),
                ('computer_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.computer_category')),
                ('game_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game_category')),
            ],
        ),
        migrations.CreateModel(
            name='games_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=999)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.games')),
            ],
        ),
    ]
